apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-list
  namespace: argocd
spec:
  # The list generator lets you enumerate a static set of elements (apps).
  generators:
    - list:
        elements:
          - app: nginx
            path: argocd-demos/nginx-demo     # path in repo for this app
          - app: online-shop
            path: argocd-demos/declarative_online_store_demo   # path in repo for this app
          - app: apache
            path: argocd-demos/apache_deployment-cli
          - app: chai-app
            path: argocd-demos/applicationSets   # path in repo for this app
  # Template that will be used to generate individual Application CRs
  template:
    metadata:
      # name template uses the element key 'app'
      name: '{{app}}-list'
    spec:
      project: default
      source:
        repoURL: https://github.com/vanessasara/Devops-practice-repo.git
        targetRevision: master
        path: '{{path}}'                # resolved from element
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
