apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apache-stg
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/vanessasara/Devops-practice-repo.git
    targetRevision: master
    path: cli_approach/apache_deployment-cli     # Path to apache manifests
  destination:
    server: 127.0.0.1  # from `argocd cluster list`
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
