# ─────────────────────────────────────────────────────────
# Your existing root-app is UNTOUCHED.
# These are 3 NEW child ArgoCD Applications that Kargo
# will sync against. Keep them separate from root-app.
# ─────────────────────────────────────────────────────────

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/vanessasara/Devops-practice-repo.git
    targetRevision: master
    # Kargo will update image tags in this folder
    path: envs/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: todo-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/vanessasara/Devops-practice-repo.git
    targetRevision: master
    path: envs/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: todo-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/vanessasara/Devops-practice-repo.git
    targetRevision: master
    path: envs/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: todo-prod
  syncPolicy:
    # Prod has NO automated sync — Kargo triggers it manually
    syncOptions:
      - CreateNamespace=true
