apiVersion: v1
kind: Namespace
metadata:
  name: kargo-demo
---
apiVersion: v1
kind: Namespace
metadata:
  name: todo-dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: todo-staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: todo-prod
