apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: online-shop-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/vanessasara/Devops-practice-repo.git  # Replace it with your forked repo
    targetRevision: master
    path: argocd-demos/declarative_online_store_demo
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
   
