apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-demo-prod
  namespace: nginx-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-demo-prod
  template:
    metadata:
      labels:
        app: nginx-demo-prod
    spec:
      containers:
        - name: nginx-demo-prod
          image: nginxdemos/hello:latest
          ports:
            - containerPort: 80
