apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      name: backend-pod
      namespace: todo-app
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: venisasarah/todo-backend:v1.0.1
        ports:
        - containerPort: 8000
      
