apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: todo-pipeline
spec:
  promotionPolicies:
    - stage: dev
      autoPromotionEnabled: true
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: todo-warehouse
  namespace: todo-pipeline
spec:
  subscriptions:
    - image:
        repoURL: venisasarah/todo-frontend
        imageSelectionStrategy: SemVer
        semverConstraint: ">=0.0.0"
    - image:
        repoURL: venisasarah/todo-backend
        imageSelectionStrategy: SemVer
        semverConstraint: ">=0.0.0"
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: todo-pipeline
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: todo-warehouse
      sources:
        direct: true
  promotionTemplate:
    spec:
      steps:
        - uses: git-clone
          config:
            repoURL: https://github.com/vanessasara/Devops-practice-repo.git
            checkout:
              - branch: master
                path: ./repo
        - uses: yaml-update
          config:
            path: ./repo/envs/dev/deployment.yaml
            updates:
              - key: spec.template.spec.containers.0.image
                value: ${{ imageFrom("venisasarah/todo-frontend", warehouse("todo-warehouse")).Repo }}:${{ imageFrom("venisasarah/todo-frontend", warehouse("todo-warehouse")).Tag }}
        - uses: git-commit
          as: commit
          config:
            path: ./repo
            message: "chore: promote to dev"
        - uses: git-push
          config:
            path: ./repo
        - uses: argocd-update
          config:
            apps:
              - name: todo-dev
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: staging
  namespace: todo-pipeline
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: todo-warehouse
      sources:
        stages:
          - dev
  promotionTemplate:
    spec:
      steps:
        - uses: git-clone
          config:
            repoURL: https://github.com/vanessasara/Devops-practice-repo.git
            checkout:
              - branch: master
                path: ./repo
        - uses: yaml-update
          config:
            path: ./repo/envs/staging/deployment.yaml
            updates:
              - key: spec.template.spec.containers.0.image
                value: ${{ imageFrom("venisasarah/todo-frontend", warehouse("todo-warehouse")).Repo }}:${{ imageFrom("venisasarah/todo-frontend", warehouse("todo-warehouse")).Tag }}
        - uses: git-commit
          as: commit
          config:
            path: ./repo
            message: "chore: promote to staging"
        - uses: git-push
          config:
            path: ./repo
        - uses: argocd-update
          config:
            apps:
              - name: todo-staging
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: todo-pipeline
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: todo-warehouse
      sources:
        stages:
          - staging
  promotionTemplate:
    spec:
      steps:
        - uses: git-clone
          config:
            repoURL: https://github.com/vanessasara/Devops-practice-repo.git
            checkout:
              - branch: master
                path: ./repo
        - uses: yaml-update
          config:
            path: ./repo/envs/prod/deployment.yaml
            updates:
              - key: spec.template.spec.containers.0.image
                value: ${{ imageFrom("venisasarah/todo-frontend", warehouse("todo-warehouse")).Repo }}:${{ imageFrom("venisasarah/todo-frontend", warehouse("todo-warehouse")).Tag }}
        - uses: git-commit
          as: commit
          config:
            path: ./repo
            message: "chore: promote to prod"
        - uses: git-push
          config:
            path: ./repo
        - uses: argocd-update
          config:
            apps:
              - name: todo-prod
