apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: todo-pipeline
  namespace: todo-pipeline
spec:
  promotionPolicies:
    - stageSelector:
        name: dev
      autoPromotionEnabled: true
