apiVersion: v1
kind: Secret
metadata:
  name: github-creds
  namespace: kargo-demo
  labels:
    kargo.akuity.io/cred-type: git
type: Opaque
stringData:
  type: git
  url: https://github.com/vanessasara/Devops-practice-repo.git
  username: vanessasara
  password: YOUR_GITHUB_PAT_TOKEN
