apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: sony-interior-warehouse
  namespace: my-app
spec:
  subscriptions:
    - image:
        repoURL: docker.io/venisasarah/sony-interior
        imageSelectionStrategy: Lexical
        allowTags: "^frontendv.*"
