apiVersion: argoproj.io/v1alpha1 
kind: Application           
metadata:                                           
  name: nginx-frontend  
  namespace: argocd             
spec:
  project: frontend-team        # Assigns app to the frontend-team Project
  source:
    repoURL: https://github.com/vanessasara/Devops-practice-repo.git
    targetRevision: master        
    path: argocd-demos/nginx-demo     # Path in repo with manifests
  destination:
    server: https://kubernetes.default.svc # Target cluster, run `argocd cluster list` to see
    namespace: frontend          # Namespace inside that cluster
  syncPolicy:                    # Sync policy settings
    automated:                   # Enable automated sync
      prune: true                 # Delete resources removed from Git
      selfHeal: true              # Correct drift if resources change in cluster
    syncOptions:                 # Additional sync options
      - CreateNamespace=true      
