apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-frontend
  namespace: todo-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-frontend
  template:
    metadata:
      labels:
        app: todo-frontend
    spec:
      containers:
      - name: todo-frontend
        image: venisasarah/todo-frontend:v1.0.2  # kargo will update this
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: todo-frontend
  namespace: todo-staging
spec:
  selector:
    app: todo-frontend
  ports:
  - port: 3000
    targetPort: 3000
