apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-demo
  namespace: sony-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-demo
  template:
    metadata:
      labels:
        app: nginx-demo
    spec:
      containers:
        - name: nginx-demo
          image: nginxdemos/hello:latest
          ports:
            - containerPort: 80
