apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: nginx-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-demo-dev
  template:
    metadata:
      labels:
        app: nginx-demo-dev
    spec:
      containers:
        - name: nginx
          image: ghcr.io/nginxinc/nginx-unprivileged:latest
          ports:
            - containerPort: 80
