apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: todo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      name: frontend-pod
      namespace: todo-app
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: venisasarah/todo-frontend:v1.0.5
        ports:
        - containerPort: 3000
        