apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: online-shop-child        # Child app name
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/vanessasara/Devops-practice-repo.git # Repo containing child apps(that you have forked and cloned earlier)
    targetRevision: main
    path: argocd-demos/declarative_online_store_demo  # path of Online Shop app in `argocd-demos` repo
  destination:
    server: https://kubernetes.default.svc # Replace with your Cluster Url, To get run: `argocd cluster list`
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
