apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-demo-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/vanessasara/Devops-practice-repo.git
    targetRevision: master
    path: mega-projects/nginx-demo/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
